# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1f73186c5b79359eb87abe3d233ab73a66313f0b2648ce224d190c5dfe1e6bb9d028790469ad26ebe1baaf55a7bd92681370fed79aef3fa2cfbde6f8e11d6da

test:
  secret_key_base: 53db03cd8868f2c6ae9934e7ad4c9a5ea3c934ab069f16179a4dfd343492a6bfa7617eacbfe31fda7d22e7a394d52bcc2a307aff922e93c2ff171c7137041100

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
